=== ribeiropdiogo/DAW2020/T2/projectrecord.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projectrecord (metadata, workteam, abstract, deliverables) >

<!ELEMENT metadata (keyname, titulo, subtitulo?, begindate, enddate, supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT begindate (#PCDATA) >
<!ELEMENT enddate (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
    link CDATA #REQUIRED >

<!ELEMENT workteam (elemento,elemento?,elemento?) >
<!ELEMENT elemento (nome,identificador,email,pagina) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT identificador (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT pagina (#PCDATA) >
<!ATTLIST pagina
    link CDATA #REQUIRED >

<!ELEMENT abstract (paragrafo)+ >
<!ELEMENT paragrafo (#PCDATA|italico|negrito|sublinhado|link)* >
<!ELEMENT italico (#PCDATA) >
<!ELEMENT negrito (#PCDATA) >
<!ELEMENT sublinhado (#PCDATA) >
<!ELEMENT link (#PCDATA) >
<!ATTLIST link
    ref CDATA #REQUIRED >
   
<!ELEMENT deliverables (deliverable)+ >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable
    link CDATA #IMPLIED >

=== ribeiropdiogo/DAW2020/T3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectrecord SYSTEM "projectrecord.dtd">
<projectrecord>
    <metadata>
        <keyname>XSL</keyname>
        <titulo>Geração de Website com transformações XSL</titulo>
        <begindate>28 de Outubro de 2020</begindate>
        <enddate>4 de Novembro de 2020</enddate>
        <supervisor link="http://www4.di.uminho.pt/~jcr/">Prof. José Carlos Ramalho</supervisor>
    </metadata>
    <workteam>
        <elemento>
            <nome>Diogo Pinto Ribeiro</nome>
            <identificador>A84442</identificador>
            <email>a84442@alunos.uminho.pt</email>
            <pagina link="https://ribeiropdiogo.tk/">ribeiropdiogo.tk</pagina>
        </elemento>
    </workteam>
    <abstract>
        <paragrafo>Neste projeto o principal objetivo foi a <negrito>geração de um website com transformações XSL</negrito>
            a partir de um dataset em XML, tendo uma página principal com o índice geral, e uma página individual
            para cada registo. Foi tido me conta a existência de campos vazios para que não fossem exibidas opções
            em branco na página do registo. Foi também estudada a possibilidade de ter a opção de avançar para páginas
            seguintes, embora sem sucesso.</paragrafo>
    </abstract>
    <deliverables>
        <deliverable link="arq.xsl">Ficheiro XSL</deliverable>
        <deliverable link="arq.dtd">Ficheiro DTD</deliverable>
    </deliverables>
</projectrecord>

=== ribeiropdiogo/DAW2020/T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectrecord SYSTEM "projectrecord.dtd">
<projectrecord>
    <metadata>
        <keyname>dtd</keyname>
        <titulo>Especificação de DTD para Project Record's</titulo>
        <begindate>21 de Outubro de 2020</begindate>
        <enddate>28 de Outubro de 2020</enddate>
        <supervisor link="http://www4.di.uminho.pt/~jcr/">Prof. José Carlos Ramalho</supervisor>
    </metadata>
    <workteam>
        <elemento>
            <nome>Diogo Pinto Ribeiro</nome>
            <identificador>A84442</identificador>
            <email>a84442@alunos.uminho.pt</email>
            <pagina link="https://ribeiropdiogo.tk/">ribeiropdiogo.tk</pagina>
        </elemento>
    </workteam>
    <abstract>
        <paragrafo>Neste projeto o principal objetivo foi a <negrito>especificação de um ficheiro dtd</negrito> para e elaboração de <italico>Project Record's</italico> no <negrito>formato XML</negrito>.</paragrafo>
    </abstract>
    <deliverables>
        <deliverable link="projectrecord.dtd">Ficheiro DTD</deliverable>
        <deliverable link="pr.xml">Ficheiro XML</deliverable>
    </deliverables>
</projectrecord>
